version: "3.5"
services:
    db:
        image: postgres
        hostname: db
        environment:
            POSTGRES_DB: "beth-stack"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
            - postgres_data:/var/lib/postgresql/data
        command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
        ports:
            - 5432:5432

networks:
    default:
        driver: bridge
        name: "beth-stack"

volumes:
    postgres_data:
